/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedCollectionsIndexImport } from './routes/_authed/collections/index'
import { Route as AuthedCollectionsCollectionIdIndexImport } from './routes/_authed/collections/$collectionId/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedCollectionsIndexRoute = AuthedCollectionsIndexImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedCollectionsCollectionIdIndexRoute =
  AuthedCollectionsCollectionIdIndexImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => AuthedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/collections/': {
      id: '/_authed/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthedCollectionsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/collections/$collectionId/': {
      id: '/_authed/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof AuthedCollectionsCollectionIdIndexImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedCollectionsIndexRoute: typeof AuthedCollectionsIndexRoute
  AuthedCollectionsCollectionIdIndexRoute: typeof AuthedCollectionsCollectionIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCollectionsIndexRoute: AuthedCollectionsIndexRoute,
  AuthedCollectionsCollectionIdIndexRoute:
    AuthedCollectionsCollectionIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/collections': typeof AuthedCollectionsIndexRoute
  '/collections/$collectionId': typeof AuthedCollectionsCollectionIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/collections': typeof AuthedCollectionsIndexRoute
  '/collections/$collectionId': typeof AuthedCollectionsCollectionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/collections/': typeof AuthedCollectionsIndexRoute
  '/_authed/collections/$collectionId/': typeof AuthedCollectionsCollectionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/collections' | '/collections/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/collections' | '/collections/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/collections/'
    | '/_authed/collections/$collectionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/collections/",
        "/_authed/collections/$collectionId/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/collections/": {
      "filePath": "_authed/collections/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/collections/$collectionId/": {
      "filePath": "_authed/collections/$collectionId/index.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
