/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as appDashboardImport } from './routes/(app)/_dashboard'
import { Route as appDashboardCollectionsIndexImport } from './routes/(app)/_dashboard/collections/index'
import { Route as appDashboardCollectionsCollectionIdIndexImport } from './routes/(app)/_dashboard/collections/$collectionId/index'

// Create Virtual Routes

const appImport = createFileRoute('/(app)')()

// Create/Update Routes

const appRoute = appImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appDashboardRoute = appDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => appRoute,
} as any)

const appDashboardCollectionsIndexRoute =
  appDashboardCollectionsIndexImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => appDashboardRoute,
  } as any)

const appDashboardCollectionsCollectionIdIndexRoute =
  appDashboardCollectionsCollectionIdIndexImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => appDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_dashboard': {
      id: '/(app)/_dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appDashboardImport
      parentRoute: typeof appRoute
    }
    '/(app)/_dashboard/collections/': {
      id: '/(app)/_dashboard/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof appDashboardCollectionsIndexImport
      parentRoute: typeof appDashboardImport
    }
    '/(app)/_dashboard/collections/$collectionId/': {
      id: '/(app)/_dashboard/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof appDashboardCollectionsCollectionIdIndexImport
      parentRoute: typeof appDashboardImport
    }
  }
}

// Create and export the route tree

interface appDashboardRouteChildren {
  appDashboardCollectionsIndexRoute: typeof appDashboardCollectionsIndexRoute
  appDashboardCollectionsCollectionIdIndexRoute: typeof appDashboardCollectionsCollectionIdIndexRoute
}

const appDashboardRouteChildren: appDashboardRouteChildren = {
  appDashboardCollectionsIndexRoute: appDashboardCollectionsIndexRoute,
  appDashboardCollectionsCollectionIdIndexRoute:
    appDashboardCollectionsCollectionIdIndexRoute,
}

const appDashboardRouteWithChildren = appDashboardRoute._addFileChildren(
  appDashboardRouteChildren,
)

interface appRouteChildren {
  appDashboardRoute: typeof appDashboardRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appDashboardRoute: appDashboardRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof appDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/collections': typeof appDashboardCollectionsIndexRoute
  '/collections/$collectionId': typeof appDashboardCollectionsCollectionIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof appDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/collections': typeof appDashboardCollectionsIndexRoute
  '/collections/$collectionId': typeof appDashboardCollectionsCollectionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(app)': typeof appRouteWithChildren
  '/(app)/_dashboard': typeof appDashboardRouteWithChildren
  '/(app)/_dashboard/collections/': typeof appDashboardCollectionsIndexRoute
  '/(app)/_dashboard/collections/$collectionId/': typeof appDashboardCollectionsCollectionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/collections' | '/collections/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/collections' | '/collections/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(app)'
    | '/(app)/_dashboard'
    | '/(app)/_dashboard/collections/'
    | '/(app)/_dashboard/collections/$collectionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  appRoute: typeof appRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  appRoute: appRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/(app)"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/(app)": {
      "filePath": "(app)",
      "children": [
        "/(app)/_dashboard"
      ]
    },
    "/(app)/_dashboard": {
      "filePath": "(app)/_dashboard.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/_dashboard/collections/",
        "/(app)/_dashboard/collections/$collectionId/"
      ]
    },
    "/(app)/_dashboard/collections/": {
      "filePath": "(app)/_dashboard/collections/index.tsx",
      "parent": "/(app)/_dashboard"
    },
    "/(app)/_dashboard/collections/$collectionId/": {
      "filePath": "(app)/_dashboard/collections/$collectionId/index.tsx",
      "parent": "/(app)/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
